### ISSUE TITLE
Community fork for Curse please

### ISSUE THREAD

**Issue by Voxxel** [frozn/TipTac#106]
Could you allow us to find and update your version of TipTac through Curseforge, please?

Similar to what Chris made for Silverwind's idTip:
https://www.curseforge.com/wow/addons/idtip-community-fork

Thanks!

**Comment by frozn** [comment]
The community fork for idTip has been approved by curseforge because of the BSD license being set by the original author. In case of TipTac the author set the "All Rights Reserved" license, where forking will (usually) be rejected by curseforge if there's no approval by the original author.

**Comment by Voxxel** [comment]
:(

**Comment by Vilogity** [comment]
Hello frozn
First THX for your Work on this !!!!!
I think you make a lot of changes on this and it's not the same anymore from last update in 2020.......

I also wrote a message to the Author before 15 Month or so, but no answer.........
See this here: https://www.curseforge.com/wow/addons/tiptac-classic
This is the same like your's from the same Author he made for Classic, and now this guy capture it and make this for Classic. ?!
I dont know what you all have changed on the code Base, but, I think it was a lot and it's maybe 50% new or more ?
So, maybe you can do the same like [DaMaGepy].
His only comment to this Classic Version is:
### I only fixed the addon for classic (and fixed some bug which I dont know if exists in retail) and added a few extra feature that others requested, but I don't plan to develop it further or to add more features if unless they are really needed.
### The original author is [Aezay](https://www.curseforge.com/members/aezay/) who created the [Retail version](https://www.curseforge.com/wow/addons/tip-tac) of this addon (last changed in march 2019) 

So I dont know the difference....maybe you can take the same Name with TipTac-DF or so.......

Greetings and THX for hold this running :-)

**Comment by frozn** [comment]
I have seen TipTac Classic from DaMaGepy, too. Apart from the fact that some features have been added, the "normal" TipTac also supports Classic. Seems redundant to me.

I created the new project "TipTac Reborn" on curseforge. Let's see what the moderator says... :crossed_fingers:

**Comment by Dubwize** [comment]
They have to see the original author is absent, and with multiple attempts to contact them has failed.   Hopefully they will be reasonable, imo TipTac is  must have addon for wow.

thanks for all the hard work on it.
- noxonix

**Comment by Voxxel** [comment]
> Let's see what the moderator says

Did they acted on it somehow? I still can't see your TipTac project curse.

**Comment by Voxxel** [comment]
> I created the new project "TipTac Reborn" on curseforge. Let's see what the moderator says... 🤞

I still don't see your project on CF. Did they reject it already or what's going on?

**Comment by frozn** [comment]
I created the new project on curseforge here: https://www.curseforge.com/wow/addons/tiptac-reborn

But it's only visible to me unless it has been approved by a moderator.

And today I received the following message:

> Hey, can you please provide the permission of the original owner to fork their project?
> 
> If you have any questions please contact our support team https://support.curseforge.com/.

I will send a message to them including the attempts to contact the owner and the fact that he hasn't been online since Jan 2022. As I wrote above, I think that creating a follow-up project on curseforge will probably not be possible due to license reasons.

I will post here again, when I get an answer. :expressionless:

**Comment by Vilogity** [comment]
So, post this to the curse guys.........

Post 2920 24.10.2020
Hello, TipTac author here.

First, I just want to let you all know that I am amazed that so many people still have an interest in TipTac. I'm also very grateful for those of you who has been trying to fix the addon by posting code snippets, or alternative downloads for a fixed version.

You're all probably wondering if I am going to update TipTac. And so far, I really don't know. The thing is, I haven't played WoW in almost a decade, so having to keep my addons up to date with new expansions, is not only difficult since I no longer play, but also somewhat of a chore.
To be honest, I've been considering retiring my addons, but seeing how many of you are still enjoying them, it doesn't seem like a nice thing to do, plus I don't like seeing my addons "die".

**What the best path for the future is, I don't know. Maybe it would be best if I handed over TipTac for someone else to maintain, or perhaps it's better just to retire the addon, since that would "force" people to find an alternative addon, an addon still maintained by someone active in WoW.**
Let me think of something, and I will post back in the coming week or so.

**Comment by Vilogity** [comment]
See here the next one.....
https://www.curseforge.com/wow/addons/tinytooltip-reforged
Also with "All Rights Reserved" license

**Comment by Dubwize** [comment]
So yeah.  :D

![image](https://user-images.githubusercontent.com/16105140/200631183-24c09e21-a6b3-45b4-be4a-ffe0fb9b9a37.png)

**Comment by Voxxel** [comment]
Omg finally!  Grats on it!
Somehow it's not available on my curse client yet.  Not for Retail, neither for Beta.
![Untitled](https://user-images.githubusercontent.com/3882152/200633480-2ab1c425-5ce7-4fb5-97b8-a16b9554a2a3.png)

**Comment by Dubwize** [comment]
hmm doesn't show with a search on mine either.   not sure how I got it, it showed up automagically.
![image](https://user-images.githubusercontent.com/16105140/200633877-a2be056d-423a-4a1b-a393-d8a32829be34.png)

**Comment by Voxxel** [comment]
We're so eager as responded in such a jiffy :P

**Comment by Voxxel** [comment]
Nothing here yet too:

https://www.curseforge.com/wow/addons/search?search=tiptac

**Comment by Vilogity** [comment]
Hmm I only see 22.11.04 for TipTac with a Date of November 2020 ??

**Comment by Voxxel** [comment]
So it is miracuously popped in my addon list without even installing it from CF client so I have both now. :P When checking the details in the client, it has no changelog, no versions, and linked to a non-existent curseforge link.
![Névtelen](https://user-images.githubusercontent.com/3882152/200815741-e7272629-f8fe-4487-b784-ea7bf62630de.png)

**Comment by Voxxel** [comment]
So, you just uploaded a new version 8 hours ago but there's no update in the CF client. Also, the project page is still a 404.

**Comment by frozn** [comment]
The was no release 8 hours ago. I'm currently working on a new release, but the latest release is from 4.11.. I still have no answer from curseforge team regarding the follow-up project "TipTac Reborn".

**Comment by Voxxel** [comment]
Mhm, I see some updates on the project page:

![Untitled](https://user-images.githubusercontent.com/3882152/201518861-0a69b38d-f643-4106-bd88-0d1c040e2170.png)

**Comment by frozn** [comment]
Yes, this are commits to the actual dev version, but I haven't bundled them yet in a new [release](https://github.com/frozn/TipTac/releases).

**Comment by Voxxel** [comment]
So the CF project page is finally up and available, people can find it through the CF web search box. Thank you for all your hard work to keep up this brilliant addon!

**Comment by frozn** [comment]
I received the following answer from the support team on curseforge:

> Hey, we approved your project, but we reserve the right to deny it if the original owner of "TipTac" asks for it. Good luck!

That are really great news! 🥳 🥳 🥳 

So the follow-up project `TipTac Reborn` is now officially available on curseforge:

https://www.curseforge.com/wow/addons/tiptac-reborn
