### ISSUE TITLE
Issue with mounts in action bars

### ISSUE THREAD

**Issue by shlwow** [frozn/TipTac#112]
Hello

Tiptac doesn't work when mousing over mounts in actions bars
Picture attached is what i got

![unknown](https://user-images.githubusercontent.com/116847892/198406055-7f483591-c3ac-4ca4-94d8-171d8ed27ef4.png)

**Comment by shlwow** [comment]
Just saw that i have the same issue with paladin aura and all spells that are on cd

**Comment by frozn** [comment]
I have seen this sometimes, too. But can't reproduce it every time, so debugging is currently not possible. :slightly_frowning_face:

**Comment by DaleHuntGB** [comment]
I have had this all day, basically hovering over anything displays the text briefly and then hides.

https://i.imgur.com/6iIMm1O.gif

**Comment by frozn** [comment]
Probably same problem with hidden scanning tooltips like here: #116

**Comment by frozn** [comment]
Summary:
The issue with the sometimes blank tooltips currently is caused by other addons using a hidden scanning tooltip to determine informations about items/spells etc. and is a bug in the current wow patch 10.0.0. This will be fixed with the upcoming wow patch 10.0.2 (currently on PTR, works fine here).
