### ISSUE TITLE
Please let me know if this is an error or not.. 

### ISSUE THREAD

**Issue by kwonjt0501** [frozn/TipTac#124]
Let me ask you one thing. Even if ToolTip Anchor is set to 'Normal Anchor' in the bag or in the map and quest list, it seems to work as 'Mouse Anchor', is this correct?
Use version "TipTac-v22.11.04-release"

**Comment by frozn** [comment]
If anchor config is set to "Normal Anchor", only tooltips using the ingame default anchor including unit tooltips will be placed to tiptac's anchor position. The tooltips in bag, map and quest list don't use blizzards default anchor and are placed near the hovered item by wow itself. There will be no override for the anchor position by TipTac because this gives a better result.

But if anchor config is set to "Mouse Anchor", there are dedicated overrides within TipTac to mouse anchor also the tooltips for bag, map and quest list etc.
