### ISSUE TITLE
Tooltip content dissappears

### ISSUE THREAD

**Issue by mjuopperi** [frozn/TipTac#126]
After todays patch in retail, tooltip content dissappears immediately after the tooltip shows.
I'm using v22.11.04 that I installed 5 days ago, so it seems to be related to the patch.

Recording of issue: https://imgur.com/SXQ5ygZ

**Comment by mjuopperi** [comment]
Looks like this only happens when the addon Bufflehead is loaded.

The addon is out of date, so probably not worth investigating this here.

**Comment by frozn** [comment]
Some addons use hidden scanning tooltips to determine infos about items, spells etc. Currently under 10.0.0 they're still working, but accidentally on blizzards side have an impact on the current displaying tooltip so that the content disappears.

With patch 10.0.2 (currently on ptr) they won't work any longer and the GameTooltip works fine again. But unfortunately TipTac needs an overhaul then too, because there are a lots of changes regarding the GameTooltip, see here: https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes#Tooltip_Changes
