### ISSUE TITLE
Error causing spells not to be able to cast

### ISSUE THREAD

**Issue by Azerox050** [frozn/TipTac#148]
**Describe the bug**
Gives an error  and cant use any buttons till i disable addon.
It says Tiptac prevented something.

**To Reproduce**
Play game, spamm buttons, error.

**Expected behavior**
No error.

**Screenshots**
-

**TipTac Reborn (please complete the following information):**
22.11.25

**WoW (please complete the following information):**
retail

**Additional context**
I disabled tiptac but the error says something: Tiptac has prevented Blizzard UI things to happen

**Comment by xathian** [comment]
Yep, TipTac and GarbageProtector are 2 mods that are causing taint on the action bars CONSTANTLY for me, messing up dungeon bosses and locking out my Dragon flying abilities randomly all day. Disabled GarbageProtector since it's very minor in its use for me but I really don't want to need to disable TipTac as well.

**Comment by frozn** [comment]
Should be fixed with latest release [v23.01.23](https://github.com/frozn/TipTac/releases/tag/v23.01.23-release). Please try again with this version.
