### ISSUE TITLE
Bugs with 23.1.23 update.

### ISSUE THREAD

**Issue by Neptec1** [frozn/TipTac#176]
**Describe the bug**
Mouse anchor Y in Mouse options does not work
Previous versions Anchors and Combat options were deleted upon update

**To Reproduce**
1. Go to /tiptac
2. Click on "Mouse" option
4. See error Mouse anchor Y does not change anything.

**TipTac Reborn (please complete the following information):**
 - Version 23.1.23

**WoW (please complete the following information):**
 - Flavor:  WotLKC
 - Version  3.4.1

**Request
Please add an option to "Reactions" to not change the color of the npc depending on Reputation level.

**Comment by frozn** [comment]
Thanks for reporting this! 👍 

I accidentally set mouse anchor X offset also to mouse anchor Y offset internally. 🙈

Regarding your request with the reaction color for unit names: It's included in the latest release [v23.01.28](https://github.com/frozn/TipTac/releases/tag/v23.01.28-release). Unfortunately the fix for the mouse anchor will be included in the following release.

**Comment by Neptec1** [comment]
thanks for the answer! and thanks for the update! =)
