### ISSUE TITLE
Borders feedback

### ISSUE THREAD

**Issue by k1ck3r** [frozn/TipTac#20]
Hey Frozn,

Because i've starting using your latest commit, i would like to stop by and say few things. First of all, in the name of all people around > THANK YOU < for giving us TipTac updated ;)

So far so good, i can report that most of the things which i couldn't without are literally even better :) No matter that some of the tooltips are missing borders, they react properly. First things first: flickering problem is just matter of pointing the Anchor. 
For example until now i used to set it up on "Top Left" of the tooltip and the flickering is present on some of addons. 

Now for the feedback part. This link is showing units, which are missing borders (at least on my end):

1. Enemery NPCs
2. Neutral NPCs 
3. Neutral world vignette
4. Name of the Macros
5. (Only on the spell book) All skill icons (for Profession tab they are totally fine)
    - Skills placed on the bars are showing proper tooltip border
6. Ara Guilds/Friends has the option to use TipTac's style (and some other addons, but that's not so critical)
    - This broker addon is showing friends popup on hovering its button on the minimap or using Bazooka's integration with Ara
7. Not sure how mailbox/anvil/cooking fire are called, but those aswell don't have borders
8. Friendly NPCs
9. And last 3 screenshots are the awesome tooltips

I hope this will help you keep track of what needs to be updated. Will wait for your future releases

**Comment by frozn** [comment]
Thank you for describing your issues and your positive feedback. 👍 

But I didn't find a link to the screenshots. Is this possible missing?

**Comment by k1ck3r** [comment]
Hey mate, yeah i totally missed the screenshots - https://imgur.com/a/wzydUCN

**Comment by frozn** [comment]
Ara guilds/friends uses an own implementation for tooltip styling. They grabbed the basic code from tiptac and added it to their addon. But this doesn't work since 9.1.0. So this is out of tiptac's scope.

Regarding your missing standard border color if no special coloring is applied:

Check "Backdrop->Tip Border Color" which color is selected. Also make shure that the slider left from the color circle is on the upper side. This adjusts the transparency of the border. + means no transparency, - means full transparency (invisible).

**Comment by frozn** [comment]
If there are any additional issues, we will handle this with another/new issues. I close this one for now.
