### ISSUE TITLE
Feature Request for Item Tooltips

### ISSUE THREAD

**Issue by Grand-Warchief** [frozn/TipTac#219]
I would love the ability to see the expansion an item came from within the tooltip somewhere. I didn't play in many of the old expansions so I don't inherently recognize the origins of items. Having an icon that indicates the expansion would be VERY helpful. There are other bag related addons that have it so I know it can be found somewhere. I'm just hoping it can be added to this one. :)

**Comment by frozn** [comment]
Good idea 👍 

I added this feature and it will be included in the next release. Unfortunately it only works in retail version and not in WotLKC or classica era, because the related expansion to the item in api function [GetItemInfo()](https://wowpedia.fandom.com/wiki/API_GetItemInfo) is only available since expansion legion.

**Comment by Grand-Warchief** [comment]
Hey, I just wanted to express my gratitude not only for the fact that you spend the time looking through these threads but also for the promptness of your response. I know it must be difficult keeping up with addons and I'm sure you get a ton of requests all the time for bugs, enhancements, etc, but the fact that you took the time to look at my suggestion and implemented it really means a lot. I've been using this addon for a while now and will continue to HIGHLY recommend it to all my friends, doubly so now that I know the developers listen to their community. Thank you so much for your hard work!

**Comment by frozn** [comment]
Thanks for your kind words! 🙂

Yes, maintaing addons is really time intensive. Additionally considering all 3 wow flavors (Retail, WotlKC, Classic Era) and the changes that come with new WoW updates needs extra time, too. Because I do it in my spare time, there's even less time for actual playing. My druid still isn't at max level. 🙈

Regarding the expansion name: I also added (optionally) the expansion icon, which seems quite nice too:

![image](https://user-images.githubusercontent.com/5655881/235450165-036fb976-3f50-4b29-a0b3-ddfc4e293f90.png)

😍

**Comment by frozn** [comment]
Added with release [v23.05.01](https://github.com/frozn/TipTac/releases/tag/v23.05.01-release).
