### ISSUE TITLE
Request: Option to "Hide Experience/Reputation Bar"

### ISSUE THREAD

**Issue by F-Lambda** [frozn/TipTac#324]
### Is your feature request related to a problem? Please describe.

TipTac has the option to hide various tooltips in and out of combat, including Action Bar tooltips. However, while action bar tooltips can be hidden, the tooltips for the experience/reputation bar directly beneath cannot be hidden. It would be nice if it could be hidden as well.

### Additional context

![image](https://github.com/user-attachments/assets/4f35945c-cb19-4adc-b45c-6f3494ad5653)

**Comment by frozn** [comment]
This feature will be included in the next release. 👍

But this options will only be available in Classic Era and Cataclysm Classic, because here I can determine these kind of tips by checking the tip's owner, in this case the frame `MainMenuExpBar`. In Retail (The War Within) this isn't possible, because the owner of the status bar tooltips is the general frame `UIParent`, so that I can't determine if the tip comes from a status bar or not.

**Comment by frozn** [comment]
Figured out a away to implement this also for retail: During checking, if the tip needs to be hidden, I check the frame the mouse is currently hovering over. If this is the frame `MainStatusTrackingBarContainer`, then this tip is one from the status bar.
