### ISSUE TITLE
Error when disabling "Special->Enable Chatframe Hover Hyperlinks"

### ISSUE THREAD

**Issue by kwonjt2001** [frozn/TipTac#39]
Hello. The addon works well. Thanks for the constant update.
 In the middle of good use, the option special item
Enabling and disabling Enable ChatFrame Hover Hyperlinks throws an error. Please confirm. I'm asking through a translator, so please understand.
![error](https://user-images.githubusercontent.com/98691652/151698328-11caa519-da1b-4c58-97ae-3068dbc74d27.jpg)

**Comment by frozn** [comment]
Hey, you're right. I haven't noticed this yet because I always have the option enabled and have never turned it off. :sweat_smile:

I fixed it and committed my changes to main branch. Here's an actual development version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/7965885/TipTac-dev.zip)

Everything's working fine with this version?

**Comment by kwonjt2001** [comment]
It seems to be working fine. thank you.
