### ISSUE TITLE
[Improvement] Enemy level color is not accurate in TimeWalking dungeons

### ISSUE THREAD

**Issue by hobulian** [frozn/TipTac#53]
This week is cataclysm Timewalking week.

I found that in TW dungeons enemy tooltip level color doesn't match to it's DifficultyLevelColor. Maybe there should be some other condition for updating player's level or other method that using player effective level besides level.

**Comment by frozn** [comment]
Switched to the new color api and used `C_PlayerInfo.GetContentDifficultyCreatureForPlayer()` to determine the difficulty level color. I also considered classic, because this function isn't available here. I committed my changes to main branch.

On my side it's working fine, but I didn't try timewalking yet. What do you think?
