### ISSUE TITLE
Yoinks RaiderIO tooltip off side of LFG frame

### ISSUE THREAD

**Issue by WanderingFox** [frozn/TipTac#54]
RaiderIO attaches a tooltip to the side of the LFG frame, but it's getting yoinked to the mouse when hovering over applicants.

The tooltip in question is `RaiderIO_ProfileTooltip`

Is it possible to exclude a tooltip from TipTac's re-anchoring?

Here's what it looks like normally:
![image](https://user-images.githubusercontent.com/2967926/153526056-2f4dcad2-982b-43a8-9dcc-4bce1716248b.png)

Here's what it looks like when hovering over someone in the list:
![image](https://user-images.githubusercontent.com/2967926/153526129-ecf63aab-ad00-40cd-9147-f946ae057399.png)

Normally, it would display the hover tooltip between the LFG frame and the raiderio tooltip.

Thank you so much for keeping this addon alive BTW. It's by far and away the best tooltip customization addon out there.

**Comment by frozn** [comment]
RaiderIO anchors its `RaiderIO_ProfileTooltip` to the right of the `PVEFrame`. If the tooltip is also shown to the right of the `PVEFrame`, RaiderIO reanchors the `RaiderIO_ProfileTooltip` and put it right to the tooltip.

If "Anchors->Frame Tip Type = Mouse Anchor" is set in TipTac, TipTac moves the tooltip to the mouse position. Because the `RaiderIO_ProfileTooltip` is still anchored to the tooltip, it also moves.

In my opinion, RaiderIO normally has to check where the tooltip is anchored to to decide, if the `RaiderIO_ProfileTooltip` needs reanchoring. But I added a workaround in TipTac to solve this issue: The tooltip will not be anchored to the mouse if addon RaiderIO is loaded and the tooltip is owned by "Premade Groups->LFGList".

I committed my changes to the main branch. Here's the current dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8051587/TipTac-dev.zip)

Works fine for you with this version too?

**Comment by WanderingFox** [comment]
Doesn't seem to fix it for me unfortunately. Frame anchor set to mouse, RaiderIO loaded, once I mouse over someone in the LFGTool queue everything gets pulled to the mouse anchor :(

**Comment by WanderingFox** [comment]
had some time to test a bit more, it works for the group tooltip (that gets pulled to the mouse without moving the rio tooltip) but not for the queue tooltip (the list of people pending to join a group)

**Comment by frozn** [comment]
You're right... I also considered now the attendees if you're hosting a group. Seems fine now. Here's the actual dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/8056126/TipTac-dev.zip)

**Comment by WanderingFox** [comment]
Yup seems good. The tooltip gets pulled up a bit but I think that's another addon adding lines post-facto.

Thanks so much!

**Comment by frozn** [comment]
Sounds good. I have noticed, that the RaiderIO tooltips are also derived from the standard GameTooltip. Therefore I additionally applied TipTac's styling to these. I committed my changes to the main branch so that this enhancement will also be included in the next release. 👍
